language: python
# ===== Linux ======
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov
